project_name_override: neptune-api
package_version_override: 0.1.0
post_hooks:
  # create an empty file at py.typed to signal that the package is typed
  - "touch py.typed"
content_type_overrides:
  application/x-protobuf: application/octet-stream
